### PR TITLE
fix(npx): dispatch unknown tools to npx instead of npm

### LINKED ISSUE #815: `rtk npx` executes `npm` instead of `npx`
## Bug

`rtk npx` dispatches to `npm` instead of `npx`, breaking all `rtk npx` invocations.

## Reproduction

```bash
# npx works
$ npx cowsay hello
 _______
< hello >
 -------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

# rtk npx doesn't — verbose confirms it runs npm instead of npx
$ rtk npx -v cowsay hello
Running: npm cowsay hello
npm error Missing script: "cowsay"
npm error
npm error To see a list of scripts, run:
npm error   npm run
npm error A complete log of this run can be found in: ~/.npm/_logs/2026-03-25T11_53_23_189Z-debug-0.log
```

## Expected behavior

`rtk npx <cmd> [args]` should execute `npx <cmd> [args]`, applying only output filtering.

## Actual behavior

`rtk npx` executes `npm` instead of `npx`. Since `npm` is a different binary with different argument parsing, subcommands and their flags are misinterpreted.

## Context

- rtk: 0.31.0
- npm/npx: 11.3.0
- Node: v24.0.0
- macOS (Apple Silicon)

The rewrite hook converts `npx <cmd> [args]` → `rtk npx <cmd> [args]`, which then fails. `rtk proxy npx <cmd> [args]` works correctly as a workaround.

## Related

- #713 — scoped package parsing in `rtk npx` (different root cause, same subsystem)
- #739 — npx fallback hang on first-run approval (different symptom)
- #197 — passthrough for tools invoked via npx/bunx/pnpx

### PR DESCRIPTION
**Pull request by tmchow**
## Summary

- Fixes `rtk npx` dispatching to `npm` instead of `npx` for unrouted tools. The fallback arm of `Commands::Npx` called `npm_cmd::run`, so `rtk npx cowsay hello` tried to run `npm cowsay hello` and failed with "Missing script".
- Replaces the fallback with a plain `npx` passthrough modeled on the existing prisma generic-subcommand arm a few lines up in the same file.
- Preserves `--skip-env` (sets `SKIP_ENV_VALIDATION=1` on the spawned process, matching what `npm_cmd::run` did).

## Evidence

Demo: rtk npx cowsay hello before vs after the fix

## Test plan

- [x] `cargo fmt --all --check && cargo clippy --all-targets && cargo test` pass locally (1679 tests, 0 failed). Pre-existing clippy warnings are unrelated to this change.
- [x] Manual: installed `rtk 0.37.2` still reproduces with `npm error code ENOENT`. Rebuilt `target/debug/rtk` from this branch routes through npx and prints the cowsay output (see demo above).
- [x] Added `test_npx_unknown_tool_passthrough` next to the existing clap parsing tests to pin the parse-level contract.

## Notes

- Targets `develop` per CONTRIBUTING.md.
- No `CHANGELOG.md` edit since release-please generates entries from commit messages.
- Aware of #819 and #840 which target the same bug. Happy to close this one if a maintainer prefers either of those. This version mirrors the in-file prisma passthrough pattern, is rebased on current `develop` (post #826 layout), and preserves `--skip-env`.

Fixes #815

[Compound Engineering](https://github.com/EveryInc/compound-engineering-plugin)

### CODE REVIEW

**Comment by tmchow** [comment]
Note: the failing benchmark test is pre-existing

File: src/main.rs [hunk 1]
```diff
@@ -2058,8 +2058,22 @@ fn run_cli() -> Result<i32> {
                 "prettier" => prettier_cmd::run(&args[1..], cli.verbose)?,
                 "playwright" => playwright_cmd::run(&args[1..], cli.verbose)?,
                 _ => {
-                    // Generic passthrough with npm boilerplate filter
-                    npm_cmd::run(&args, cli.verbose, cli.skip_env)?
```
Comment (KuSh) [inline src/main.rs:2062]: Instead of duplicating code, loosing some parts (verbose at least) and adding maintenance burden, could't we have a `npm_cmd::exec` function with npm_run::run splitted between run specifics (the part computing effective_args) and a reusable part (the rest) that would be used by npm_cmd::exec too ?

Comment (tmchow) [reply src/main.rs:2062]: Pushed 09aaf55: added `runner::run_passthrough_cmd(cmd, tool, args_display, verbose)` that takes a pre-built Command (so callers can set env vars like `SKIP_ENV_VALIDATION`), and refactored the existing `run_passthrough` to delegate to it. The npx arm now builds the Command, sets the env when needed, and hands it to the shared helper.

As a bonus this also upgrades the npx passthrough from `cmd.status()` to the shared streaming + tracking path that `pnpm_cmd::run_passthrough` already uses, so verbose logging and telemetry match across tools. Tests: 1679 pass, including `test_npx_unknown_tool_passthrough`.

**Comment by tmchow** [comment]
@KuSh all fixed up

File: src/main.rs [hunk 2]
```diff
@@ -2058,8 +2058,18 @@ fn run_cli() -> Result<i32> {
...
+                    // it to the shared runner so tracking + streaming match pnpm_cmd.
+                    let mut cmd = core::utils::resolved_command("npx");
+                    for arg in &args {
+                        cmd.arg(arg);
+                    }
+                    if cli.skip_env {
+                        cmd.env("SKIP_ENV_VALIDATION", "1");
+                    }
+                    let args_str = args.join(" ");
+                    core::runner::run_passthrough_cmd(cmd, "npx", &args_str, cli.verbose)?
```
Comment (KuSh) [inline src/main.rs]: Thanks for the change but that's still not what I had in mind.

I'd prefer to have everything in src/cmds/js/npm_cmd.rs within an exec function. And here just have a `npm_cmd::exec(&args, cli.verbose, cli.skip_env)?` call.

Constructing args, handling skip_env can be mutualized. The only thing that change compared to `run` is the effective_args building and the `resolved_command` argument

So what I had in mind was:
- create a `fn run_filtered` that calls `resolved_command` with command name from params, add args from params to cmd, handle skip_env and verbose then calls `runner::run_filtered`
- update `pub fn run` to construct its effective_args and calls npm_cmd::run_filtered with 'npm' command name
- create a new `pub fn exec` that calls npm_cmd::run_filtered with 'npx' command name
- main calls npm_cmd::exec instead of npm_cmd::run for npx passthrough

**Review by KuSh — CHANGES_REQUESTED** [review]

**Comment by tmchow** [comment]
Pushed a5e6bf5: moved everything into npm_cmd. Added a private `run_filtered(name, args, verbose, skip_env)` helper that builds the command, applies `SKIP_ENV_VALIDATION`, emits the verbose log, and routes through `runner::run_filtered` with `filter_npm_output`. `pub fn run` keeps its existing `effective_args` building (run-injection logic) and calls `run_filtered("npm", ...)`. New `pub fn exec` just calls `run_filtered("npx", args, verbose, skip_env)`. The fallback in main.rs is now `npm_cmd::exec(&args, cli.verbose, cli.skip_env)?`.

One call-out: I kept `exec` routing through `runner::run_filtered` (matching npm) instead of `runner::run_passthrough_cmd`, so both share streaming + tracking and the same output filter. If you want raw passthrough on npx, swap the runner call in `run_filtered` and pass a passthrough flag, happy to do that.

Verified: `cargo test` 1679 passing (no change), `cargo clippy` clean for the changed files. Manual: rebuilt `target/release/rtk`, `rtk npx cowsay "ok"` still works, `-v` shows `Running: npx cowsay ok`.

File: src/core/runner.rs
Comment (KuSh) [inline src/core/runner.rs:1]: This part could be revert now that you don't use `run_passthrough_cmd` anymorre

**Review by KuSh — CHANGES_REQUESTED** [review]
Just one unneeded change left, otherwise LGTM!

File: src/core/runner.rs
Comment (tmchow) [reply src/core/runner.rs:1]: Reverted in d8bfca8: `src/core/runner.rs` is back to its develop state. `cargo fmt --all --check`, `cargo clippy --all-targets`, `cargo test` all pass (1679 tests, 0 failed).

**Review by KuSh — APPROVED** [review]
