### PR TITLE
fix(ccusage): add --yes flag and warn when falling back to npx

### LINKED ISSUE #1226: bug: the command cc-economics is hanging
I left like this for half a minute and nothing was outputed. Not sure if this is expected.

Image

Version:
rtk 0.35.0

OS:
MacOS Tahoe 26

### PR DESCRIPTION
**Pull request by davidalecrim1**
## Summary

- Fixes silent hang in `rtk cc-economics` when `ccusage` is not installed globally
- `npx` prompts "Ok to proceed? (y)" before installing the package — RTK's subprocess blocks on this forever since it has no interactive stdin
- Adding `--yes` auto-confirms the install
- Added an `[info]` warning to stderr so users know why it may take a moment

## Root Cause

`build_command()` falls back to `npx ccusage` when the binary isn't in PATH. Without `--yes`, npx waits for interactive confirmation that never comes.

Closes #1226

### CODE REVIEW

File: src/analytics/ccusage.rs [hunk 1]
```diff
@@ -95,7 +95,9 @@ fn build_command() -> Option<Command> {
     }
 
     // Fallback: try npx
+    eprintln!("[info] ccusage not installed globally, fetching via npx...");
```
Comment (davidalecrim1) [inline src/analytics/ccusage.rs:98]: We can remove this if doesn't make sense for the CLI UX, let me know if that's the case.

**Review by FlorianBruniaux — APPROVED** [review]
LGTM — clean fix, tests pass.
